// `ccrc expose` — Task 2 of the stage-3b exposure plan (spec D1–D3). The verb
// that gives a box a public name and a real certificate WITHOUT ever running
// sudo: it writes `~/.ccrc/exposure.env` (0600, the server unit's second
// EnvironmentFile — Task 1's seam) and `~/.ccrc/Caddyfile` (regenerated every
// run), and PRINTS the three root steps the operator must do themselves — the
// `_inst_linger` degraded-step doctrine applied to a whole verb.
//
// `ccrc-cli.test.ts` owns the verb's DISCOVERABILITY (the usage line);
// `single-definition.test.ts` pins that the two paths are spelled once each
// (`CCRC_EXPOSURE_FILE`, `CCRC_CADDYFILE`); this file owns what the verb DOES.
//
// ── HOW THE FIXTURE CONTAINS IT (the ccrc-passwd.test.ts harness) ─────────
//  1. HOME is a throwaway `mkTmp` directory — the isolation boundary the whole
//     ccd/ccrc suite relies on (CLAUDE.md). `ccrc expose` WRITES `$HOME/.ccrc`,
//     which on the box this suite runs on holds live config.
//  2. `ccrc` is invoked through a symlink at `<home>/ccrc/ccd/ccrc` — the
//     shape of a deployed box.
//  3. `ghContainedEnv` plants the poisoned `gh`, and `curl`/`systemctl` are
//     poisoned beside it (ccrc-cli.test.ts's `ccrcEnv` idiom) — not because
//     Task 2's verb shells out to any of them, but because Task 3's duckdns
//     arm WILL run `systemctl --user`, on top of this same runner.
//  4. `caddy` is deliberately NOT stubbed: the verb never executes it — it
//     only writes the file caddy will read once the OPERATOR has armed it.
import { describe, it, expect } from 'vitest';
import { spawnSync } from 'node:child_process';
import {
  existsSync, mkdirSync, readFileSync, readdirSync, symlinkSync, writeFileSync, statSync,
} from 'node:fs';
import path, { join } from 'node:path';
import { fileURLToPath } from 'node:url';
import * as pty from 'node-pty';
import { mkTmp } from './tmpHelpers.js';
import { ghContainedEnv } from './ccdWsHelpers.js';
import { itLinux, itDarwin } from './platformFixtures.js';

const here = path.dirname(fileURLToPath(import.meta.url));
const REPO = path.resolve(here, '..', '..');
const CCRC_SRC = join(REPO, 'ccd', 'ccrc');

/** bash's absolute path, resolved once under this process's real PATH. */
const BASH = spawnSync('bash', ['-c', 'command -v bash'], { encoding: 'utf8' }).stdout.trim();

const SUB = 'mybox';
const HOST = `${SUB}.duckdns.org`;
const TOKEN = 'fixture-duckdns-token-9c2e41';   // a FIXTURE value, never a real credential
const BYO_ORIGIN = 'https://box.example.com';
const BYO_RPID = 'box.example.com';
const IP_ADDR = '198.51.100.7';                 // TEST-NET-2 — the fixture box's "global" address

const ccrcIn = (home: string): string => join(home, 'ccrc', 'ccd', 'ccrc');
const exposurePath = (home: string): string => join(home, '.ccrc', 'exposure.env');
const caddyfilePath = (home: string): string => join(home, '.ccrc', 'Caddyfile');
const envFilePath = (home: string): string => join(home, '.ccrc', 'ccrc.env');

/** The exact bytes the duckdns arm writes — asserted whole, because the file
 *  is an EnvironmentFile the server unit sources and a stray character is a
 *  key systemd never sets. */
const duckdnsEnv = (sub: string, token: string, bind = ''): string => [
  "# ccrc exposure config — regenerated by 'ccrc expose'; delete it to go dark.",
  `CCRC_ORIGIN=https://${sub}.duckdns.org`,
  `CCRC_RP_ID=${sub}.duckdns.org`,
  'CCRC_AUTH=on',
  ...(bind ? [`CCRC_CADDY_BIND=${bind}`] : []),
  'CCRC_DDNS_PROVIDER=duckdns',
  `CCRC_DDNS_DOMAIN=${sub}.duckdns.org`,
  `CCRC_DDNS_TOKEN=${token}`,
].join('\n') + '\n';

const byoEnv = (origin: string, rpid: string, bind = ''): string => [
  "# ccrc exposure config — regenerated by 'ccrc expose'; delete it to go dark.",
  `CCRC_ORIGIN=${origin}`,
  `CCRC_RP_ID=${rpid}`,
  'CCRC_AUTH=on',
  ...(bind ? [`CCRC_CADDY_BIND=${bind}`] : []),
].join('\n') + '\n';

/** The ip arm's file (stage 5, S10): NO CCRC_RP_ID — an rpId must be a domain
 *  (webauthn.ts refuses an address literal), so the key is omitted, never
 *  written empty — plus the mode and the measured address, so doctor and a
 *  re-run judge the same box the verb did. */
const ipEnv = (addr: string, bind = ''): string => [
  "# ccrc exposure config — regenerated by 'ccrc expose'; delete it to go dark.",
  `CCRC_ORIGIN=https://${addr}`,
  'CCRC_AUTH=on',
  'CCRC_EXPOSE_MODE=ip',
  `CCRC_EXPOSE_ADDR=${addr}`,
  ...(bind ? [`CCRC_CADDY_BIND=${bind}`] : []),
].join('\n') + '\n';

/** The Caddyfile is exactly this (spec D1): stock Caddy automatic HTTPS does
 *  everything else. No TLS directives, no plugin syntax. The optional `bind`
 *  (D-163) is the ONE line an operator used to have to add by hand — and lose
 *  to the next regeneration. */
const caddyfile = (host: string, port: number, bind = ''): string =>
  `${host} {\n${bind ? `    bind ${bind}\n` : ''}    reverse_proxy 127.0.0.1:${port}\n}\n`;

/** The ip arm's Caddyfile (spec §7): the scheme stated, `tls internal` saying
 *  who signs — caddy's own CA, no ACME, nothing leaves the box. */
const ipCaddyfile = (addr: string, port: number, bind = ''): string =>
  `https://${addr} {\n${bind ? `    bind ${bind}\n` : ''}    tls internal\n    reverse_proxy 127.0.0.1:${port}\n}\n`;

/** A box with the tree `ccrc expose` needs and nothing in `~/.ccrc` yet. The
 *  tree carries `deploy/systemd/` too (a symlink to the repo's): Task 3's
 *  duckdns arm installs the ddns unit TEMPLATES out of the tree it runs from
 *  (`_inst_enable`'s `$CCRC_HERE/..` idiom), and a fixture tree without them
 *  would red every arm on "is this a complete ccrc tree?". */
function box(prefix: string): string {
  const home = mkTmp(prefix);
  const ccd = join(home, 'ccrc', 'ccd');
  mkdirSync(ccd, { recursive: true });
  symlinkSync(CCRC_SRC, join(ccd, 'ccrc'));
  mkdirSync(join(home, 'ccrc', 'deploy'), { recursive: true });
  symlinkSync(join(REPO, 'deploy', 'systemd'), join(home, 'ccrc', 'deploy', 'systemd'));
  return home;
}

/** `systemctlOk`: replace the poison with a stub that RECORDS argv (one line
 *  per call, to `$HOME/systemctl-argv`) and succeeds — the happy-path shape of
 *  a box with a session bus. The default stays the poison: exit 97 IS a test —
 *  the degraded arm — and containment besides. */
function env(home: string, opts: { systemctlOk?: boolean; launchctlOk?: boolean } = {}): NodeJS.ProcessEnv {
  const e = ghContainedEnv(home, { ...process.env, HOME: home });
  // curl and systemctl are poisoned the way ccrc-cli.test.ts poisons them —
  // Task 3's duckdns arm runs `systemctl --user`, and containment each test
  // has to remember is containment that goes missing.
  const poison = (name: string, says: string): void =>
    writeFileSync(join(home, '.local', 'bin', name),
      `#!/bin/sh\nprintf '%s\\n' "$*" >> "$HOME/${name}-poison"\n`
      + `echo "${says}" >&2\nexit 97\n`, { mode: 0o755 });
  poison('curl', 'ccrc tests must never reach a real server');
  if (opts.systemctlOk) {
    writeFileSync(join(home, '.local', 'bin', 'systemctl'),
      '#!/bin/sh\nprintf \'%s\\n\' "$*" >> "$HOME/systemctl-argv"\nexit 0\n', { mode: 0o755 });
  } else {
    poison('systemctl', 'ccrc tests must never touch this box\'s real systemd');
  }
  // launchctl needs no poison: without a stub on PATH, the platform layer's
  // own sandbox-HOME guard refuses the call before any binary runs (that is
  // itself a tested property, macos-platform.test.ts). `launchctlOk` is the
  // Darwin twin of `systemctlOk` — a recorder for the argv-order pins.
  if (opts.launchctlOk) {
    writeFileSync(join(home, '.local', 'bin', 'launchctl'),
      '#!/bin/sh\nprintf \'%s\\n\' "$*" >> "$HOME/launchctl-argv"\nexit 0\n', { mode: 0o755 });
  }
  for (const k of ['CCRC_ADDR', 'CCRC_HEALTH_TIMEOUT', 'CCRC_DOCTOR_GH_TIMEOUT']) delete e[k];
  return e;
}

/** `hostname -I` answers the given line — the ip arm's ONE measurement. The
 *  real binary would answer this box's real addresses: a live value in a
 *  fixture, and a different one on every runner. `null` = the flag fails
 *  (a box whose hostname has no -I, or none at all — the same emptiness). */
function stubHostname(home: string, line: string | null): void {
  mkdirSync(join(home, '.local', 'bin'), { recursive: true });
  writeFileSync(join(home, '.local', 'bin', 'hostname'),
    line === null
      ? '#!/bin/sh\nexit 1\n'
      : `#!/bin/sh\nif [ "$1" = "-I" ]; then printf '%s\\n' "${line}"; exit 0; fi\nexit 1\n`,
    { mode: 0o755 });
}

interface Result { code: number; stdout: string; stderr: string }

/** `ccrc <args>` with stdin NOT a terminal — the shape the tty refusal exists
 *  for, and (with `''`) the shape of every non-interactive invocation. */
function runPiped(home: string, args: string[], stdin = ''): Result {
  const r = spawnSync(BASH, [ccrcIn(home), ...args],
    { env: env(home), encoding: 'utf8', input: stdin });
  return { code: r.status ?? -1, stdout: r.stdout ?? '', stderr: r.stderr ?? '' };
}

/** The four prompt heads the verb can print; one entry is sent per prompt SEEN
 *  (ccrc-passwd.test.ts's `runPasswdTty` synchronisation, generalised). */
const PROMPTS = /(DuckDNS subdomain|DuckDNS token|Public origin|Passkey rp id|Address for caddy to bind)/g;

/** `ccrc expose <args>` on a REAL terminal, typing `entries` at the prompts.
 *  A pty because `[ -t 0 ]` and `read -rs` are two of the things this verb IS:
 *  without a terminal the only reachable branch is the refusal. */
function runExposeTty(
  home: string, args: string[], entries: string[],
  opts: { systemctlOk?: boolean; launchctlOk?: boolean } = {},
): Promise<Result> {
  return new Promise((resolve) => {
    const p = pty.spawn(BASH, [ccrcIn(home), 'expose', ...args], {
      name: 'xterm-color', cols: 200, rows: 40, cwd: home,
      env: env(home, opts) as Record<string, string>,
    });
    let out = '';
    let sent = 0;
    let done = false;
    const finish = (code: number): void => {
      if (done) return;
      done = true;
      clearTimeout(timer);
      resolve({ code, stdout: out, stderr: '' });   // a pty merges the two streams
    };
    const timer = setTimeout(() => { p.kill(); finish(-1); }, 20_000);
    p.onData((d) => {
      out += d;
      const prompts = (out.match(PROMPTS) ?? []).length;
      while (sent < prompts && sent < entries.length) p.write(`${entries[sent++]}\r`);
    });
    p.onExit(({ exitCode }) => finish(exitCode));
  });
}

/** The file's exact bytes, or `null` when there is none. */
const bytesAt = (p: string): string | null => (existsSync(p) ? readFileSync(p, 'utf8') : null);

/** Everything in `~/.ccrc` — the assertion that a refusal left no temp file
 *  behind either. An `exposure.env.tmp.<pid>` holding a live token is not a
 *  leak of nothing. */
const ccrcDirEntries = (home: string): string[] => {
  const d = join(home, '.ccrc');
  return existsSync(d) ? readdirSync(d).sort() : [];
};

const mode = (p: string): number => statSync(p).mode & 0o777;

// ── dispatch: the verb-table idiom ────────────────────────────────────────

describe('ccrc expose: dispatch', () => {
  it('with no subcommand is a usage error, exit 2 — not a default arm that quietly ran', () => {
    const home = box('ccrc-expose-nosub-');
    const r = runPiped(home, ['expose']);
    expect(r.code).toBe(2);
    expect(r.stderr).toMatch(/^ccrc: expose: missing subcommand \(duckdns\|byo\|ip\|status\)/m);
    expect(r.stderr).toMatch(/usage: ccrc/);
    expect(ccrcDirEntries(home)).toEqual([]);
  });

  it('an unknown subcommand is the same usage error as an unknown verb', () => {
    const home = box('ccrc-expose-unknown-');
    const r = runPiped(home, ['expose', 'wat']);
    expect(r.code).toBe(2);
    expect(r.stderr).toMatch(/^ccrc: unknown argument: wat/m);
    expect(r.stderr).toMatch(/usage: ccrc/);
    expect(ccrcDirEntries(home)).toEqual([]);
  });

  it('expose -h prints usage on STDOUT at exit 0 — a verb that changes the box explains itself first', () => {
    const home = box('ccrc-expose-help-');
    const r = runPiped(home, ['expose', '-h']);
    expect(r.code).toBe(0);
    expect(r.stdout).toMatch(/usage: ccrc \{/);
    expect(r.stderr).toBe('');
    expect(ccrcDirEntries(home)).toEqual([]);
  });

  it('extra arguments after a subcommand are a usage error too', () => {
    const home = box('ccrc-expose-extra-');
    const r = runPiped(home, ['expose', 'status', 'extra']);
    expect(r.code).toBe(2);
    expect(r.stderr).toMatch(/^ccrc: unknown argument: extra/m);
  });
});

// ── the duckdns arm ───────────────────────────────────────────────────────

describe('ccrc expose duckdns', () => {
  it('REFUSES a piped stdin — under `curl … | bash`, stdin is the installer', () => {
    // The mutation this pins: delete the `[ -t 0 ]` guard and the verb will
    // happily read a line of shell as this box's DuckDNS token.
    const home = box('ccrc-expose-piped-');
    const r = runPiped(home, ['expose', 'duckdns'], `${SUB}\n${TOKEN}\n`);
    expect(r.code).toBe(1);
    expect(r.stderr).toMatch(/^ccrc: stdin is not a terminal/m);
    expect(r.stderr).toMatch(/curl … \| bash/);
    expect(ccrcDirEntries(home)).toEqual([]);
  });

  it('writes exposure.env (0600) and the Caddyfile (0644), exactly', async () => {
    const home = box('ccrc-expose-duck-ok-');
    const r = await runExposeTty(home, ['duckdns'], [SUB, TOKEN, '']);
    expect(r.code, r.stdout).toBe(0);
    expect(bytesAt(exposurePath(home))).toBe(duckdnsEnv(SUB, TOKEN));
    expect(mode(exposurePath(home)), 'exposure.env holds a token and must be 0600').toBe(0o600);
    expect(bytesAt(caddyfilePath(home))).toBe(caddyfile(HOST, 7788));
    expect(mode(caddyfilePath(home))).toBe(0o644);
    // …and nothing else was left in ~/.ccrc — no temp file survived the mv.
    expect(ccrcDirEntries(home)).toEqual(['Caddyfile', 'exposure.env']);
  });

  it('never echoes and never prints the token — it reaches the FILE and nothing else', async () => {
    // `read -rs` at the prompt, and no line of the transcript ever carries the
    // value. The mutation this pins: drop `-s` (or echo the token back) and
    // the pty transcript contains it.
    const home = box('ccrc-expose-duck-quiet-');
    const r = await runExposeTty(home, ['duckdns'], [SUB, TOKEN, '']);
    expect(r.code, r.stdout).toBe(0);
    expect(r.stdout).not.toContain(TOKEN);
    expect(readFileSync(exposurePath(home), 'utf8')).toContain(TOKEN);
  });

  it('prints the sudo ceremony — exactly three steps, and sudo appears ONLY inside them', async () => {
    // The `_inst_linger` doctrine, verb-sized: ccrc never runs sudo; it prints
    // the exact commands and the operator runs them. The grep shape is the
    // same: every line carrying `sudo` must be a numbered remedy line.
    const home = box('ccrc-expose-duck-ceremony-');
    const r = await runExposeTty(home, ['duckdns'], [SUB, TOKEN, '']);
    expect(r.code, r.stdout).toBe(0);
    expect(r.stdout).toMatch(/1\. install caddy/);
    expect(r.stdout).toMatch(/2\. sudo install -m 0644 .*Caddyfile \/etc\/caddy\/Caddyfile/);
    expect(r.stdout).toMatch(/3\. sudo systemctl enable --now caddy/);
    // D-165. This assertion used to REQUIRE the symlink form — the ceremony
    // shipped it for a month and it cannot work: caddy runs as its own user
    // and `$HOME`/`$HOME/.ccrc` are 750/700 (the 700 is ccrc's own doing), so
    // the link resolves to a file caddy may not read and it fails to load
    // with a permission error nowhere near this instruction. Inverted into a
    // guard: printing a symlink here again is the defect.
    expect(r.stdout, 'the symlink ceremony is unreachable by the caddy user')
      .not.toMatch(/ln -s/);
    expect(r.stdout).not.toMatch(/^expose: {3}4\./m);
    for (const line of r.stdout.split(/\r?\n/).filter((l) => l.includes('sudo'))) {
      expect(line, 'sudo outside the printed remedy').toMatch(/^expose: {3}[23]\. sudo /);
    }
  });

  it('lands degraded-style: names the port-forward prerequisite and the ccrc restart', async () => {
    const home = box('ccrc-expose-duck-landing-');
    const r = await runExposeTty(home, ['duckdns'], [SUB, TOKEN, '']);
    expect(r.code, r.stdout).toBe(0);
    expect(r.stdout).toMatch(/forward ports 80 and 443/);
    // The remedy names a command THIS box has — `systemctl --user restart` on
    // macOS is a second dead end printed at the moment somebody is already
    // following instructions. What is pinned is that the restart is named.
    expect(r.stdout).toMatch(process.platform === 'darwin'
      ? /launchctl kickstart -k gui\/\d+\/app\.ccrc\.ccrc/
      : /systemctl --user restart ccrc\.service/);
  });

  it('reads CCRC_PORT from ccrc.env for the Caddyfile — 7788 is the default, not a constant', async () => {
    const home = box('ccrc-expose-duck-port-');
    mkdirSync(join(home, '.ccrc'), { recursive: true });
    writeFileSync(envFilePath(home), 'CCRC_PORT=9999\n');
    const r = await runExposeTty(home, ['duckdns'], [SUB, TOKEN, '']);
    expect(r.code, r.stdout).toBe(0);
    expect(bytesAt(caddyfilePath(home))).toBe(caddyfile(HOST, 9999));
  });

  it('refuses a subdomain that is not one bare label, and writes nothing', async () => {
    const home = box('ccrc-expose-duck-badsub-');
    const r = await runExposeTty(home, ['duckdns'], ['my.box']);
    expect(r.code).toBe(1);
    expect(r.stdout).toMatch(/not a bare DuckDNS subdomain/);
    expect(ccrcDirEntries(home)).toEqual([]);
  });

  it('is idempotent: a second run with the same answers is byte-identical', async () => {
    const home = box('ccrc-expose-duck-idem-');
    expect((await runExposeTty(home, ['duckdns'], [SUB, TOKEN, ''])).code).toBe(0);
    const envBefore = bytesAt(exposurePath(home));
    const caddyBefore = bytesAt(caddyfilePath(home));
    const r = await runExposeTty(home, ['duckdns'], [SUB, TOKEN, '']);
    expect(r.code, r.stdout).toBe(0);
    expect(bytesAt(exposurePath(home))).toBe(envBefore);
    expect(bytesAt(caddyfilePath(home))).toBe(caddyBefore);
  });

  it('re-running with NEW answers rewrites both files — the REGENERATE class', async () => {
    const home = box('ccrc-expose-duck-rerun-');
    expect((await runExposeTty(home, ['duckdns'], [SUB, TOKEN, ''])).code).toBe(0);
    const r = await runExposeTty(home, ['duckdns'], ['otherbox', 'other-token-1a2b3c', '']);
    expect(r.code, r.stdout).toBe(0);
    expect(bytesAt(exposurePath(home))).toBe(duckdnsEnv('otherbox', 'other-token-1a2b3c'));
    expect(bytesAt(caddyfilePath(home))).toBe(caddyfile('otherbox.duckdns.org', 7788));
  });
});

// ── the shadow refusal (spec D3) ──────────────────────────────────────────

describe('ccrc expose: the shadow refusal', () => {
  // The 3a hand-edit path: an operator who set CCRC_ORIGIN/CCRC_RP_ID in
  // ccrc.env directly. The server unit reads exposure.env SECOND, so a key in
  // both files is silently won by this verb's — the exact overloaded-seam
  // shape the codebase bans. The verb refuses, names both files and which
  // would win, and writes NOTHING. Mutation: delete the refusal → red here.
  for (const key of ['CCRC_ORIGIN', 'CCRC_RP_ID'] as const) {
    it(`refuses when ccrc.env already sets ${key}, naming both files and the winner`, () => {
      const home = box(`ccrc-expose-shadow-${key.toLowerCase()}-`);
      mkdirSync(join(home, '.ccrc'), { recursive: true });
      writeFileSync(envFilePath(home),
        key === 'CCRC_ORIGIN' ? 'CCRC_ORIGIN=https://old.example.com\n' : 'CCRC_RP_ID=old.example.com\n');
      const r = runPiped(home, ['expose', 'duckdns'], `${SUB}\n${TOKEN}\n`);
      expect(r.code).toBe(1);
      expect(r.stderr).toContain(key);
      expect(r.stderr).toContain(envFilePath(home));
      expect(r.stderr).toContain(exposurePath(home));
      expect(r.stderr).toMatch(/wins|would win/);
      expect(existsSync(exposurePath(home))).toBe(false);
      expect(existsSync(caddyfilePath(home))).toBe(false);
    });
  }

  it('a bare KEY= line in ccrc.env is NOT a shadow — empty is unset, the || rule', async () => {
    // `config.ts` reads both keys with `||`, so a bare `CCRC_ORIGIN=` line is
    // an unset key to the server — and must be one to this refusal too, or the
    // verb refuses over a line that decides nothing.
    const home = box('ccrc-expose-shadow-empty-');
    mkdirSync(join(home, '.ccrc'), { recursive: true });
    writeFileSync(envFilePath(home), 'CCRC_ORIGIN=\nCCRC_RP_ID=\n');
    const r = await runExposeTty(home, ['duckdns'], [SUB, TOKEN, '']);
    expect(r.code, r.stdout).toBe(0);
    expect(bytesAt(exposurePath(home))).toBe(duckdnsEnv(SUB, TOKEN));
  });
});

// ── the byo arm ───────────────────────────────────────────────────────────

describe('ccrc expose byo', () => {
  it('REFUSES a piped stdin for the same reason as duckdns — byo prompts too', () => {
    const home = box('ccrc-expose-byo-piped-');
    const r = runPiped(home, ['expose', 'byo'], `${BYO_ORIGIN}\n${BYO_RPID}\n`);
    expect(r.code).toBe(1);
    expect(r.stderr).toMatch(/^ccrc: stdin is not a terminal/m);
    expect(ccrcDirEntries(home)).toEqual([]);
  });

  it('takes the full origin and the rp id as STATED — derives nothing, installs no ddns keys', async () => {
    const home = box('ccrc-expose-byo-ok-');
    const r = await runExposeTty(home, ['byo'], [BYO_ORIGIN, BYO_RPID, '']);
    expect(r.code, r.stdout).toBe(0);
    expect(bytesAt(exposurePath(home))).toBe(byoEnv(BYO_ORIGIN, BYO_RPID));
    expect(readFileSync(exposurePath(home), 'utf8')).not.toContain('CCRC_DDNS');
    expect(mode(exposurePath(home))).toBe(0o600);
    expect(bytesAt(caddyfilePath(home))).toBe(caddyfile(BYO_RPID, 7788));
  });

  it('the rp-id prompt quotes config.ts\'s own warning — the PSL rule, in one line', async () => {
    // `config.ts`'s rpId docstring: configured and never derived, because how
    // many labels to strip needs the Public Suffix List (duckdns.org and
    // ts.net are both public suffixes). The operator states it.
    const home = box('ccrc-expose-byo-psl-');
    const r = await runExposeTty(home, ['byo'], [BYO_ORIGIN, BYO_RPID, '']);
    expect(r.code, r.stdout).toBe(0);
    expect(r.stdout).toMatch(/Public Suffix List/);
    expect(r.stdout).toMatch(/NEVER derived/);
  });

  it('refuses an origin that is not https://, and writes nothing', async () => {
    const home = box('ccrc-expose-byo-http-');
    const r = await runExposeTty(home, ['byo'], ['http://box.example.com']);
    expect(r.code).toBe(1);
    expect(r.stdout).toMatch(/not an https:\/\/ origin/);
    expect(ccrcDirEntries(home)).toEqual([]);
  });

  it('refuses an origin carrying a path — an origin is scheme and host only', async () => {
    const home = box('ccrc-expose-byo-path-');
    const r = await runExposeTty(home, ['byo'], ['https://box.example.com/pwa']);
    expect(r.code).toBe(1);
    expect(r.stdout).toMatch(/carries a path/);
    expect(ccrcDirEntries(home)).toEqual([]);
  });

  // Branch review, 2026-08-21: '?', '#' and '@' pass a browser's URL parser
  // but land verbatim in the Caddyfile site address, where Caddy refuses to
  // load — the operator's typo would otherwise surface only later, at the
  // caddy/cert doctor checks, instead of at this prompt.
  it.each([
    ['a query', 'https://box.example.com?x=1'],
    ['a fragment', 'https://box.example.com#pwa'],
    ['userinfo', 'https://me@box.example.com'],
  ])('refuses an origin carrying %s — Caddy would refuse the site address later', async (_what, origin) => {
    const home = box('ccrc-expose-byo-caddyhostile-');
    const r = await runExposeTty(home, ['byo'], [origin]);
    expect(r.code).toBe(1);
    expect(r.stdout).toMatch(/carries '\?', '#' or '@'/);
    expect(ccrcDirEntries(home)).toEqual([]);
  });
});

// ── the ip arm (stage 5, S10) — HTTPS with nobody else involved ───────────
// No DuckDNS, no domain, no ACME: the box's own bare global IPv4 as the
// origin, and caddy's INTERNAL CA (`tls internal`) signing the certificate.
// The address is MEASURED (`hostname -I`, first global IPv4 through
// `_dr_ip4_global` — the name check's own classifier), never typed; behind
// NAT/CGNAT the verb refuses, because the address browsers would reach is not
// on the box and a config certifying it would lie from birth. Passkeys need a
// domain RP ID, so no CCRC_RP_ID is written and the gate runs passphrase-only
// — the verb says exactly that, verbatim.

describe('ccrc expose ip', () => {
  it('REFUSES a piped stdin — the bind prompt reads, and under curl|bash stdin is the installer', () => {
    const home = box('ccrc-expose-ip-piped-');
    stubHostname(home, `${IP_ADDR}`);
    const r = runPiped(home, ['expose', 'ip'], '\n');
    expect(r.code).toBe(1);
    expect(r.stderr).toMatch(/^ccrc: stdin is not a terminal/m);
    expect(ccrcDirEntries(home)).toEqual([]);
  });

  it('measures the FIRST GLOBAL IPv4 itself and writes both files, exactly', async () => {
    // The interface list leads with private space — the arm must WALK the
    // answer through the classifier, not take the first token.
    const home = box('ccrc-expose-ip-ok-');
    stubHostname(home, `10.0.0.5 ${IP_ADDR} 192.168.1.9`);
    const r = await runExposeTty(home, ['ip'], ['']);
    expect(r.code, r.stdout).toBe(0);
    expect(bytesAt(exposurePath(home))).toBe(ipEnv(IP_ADDR));
    expect(mode(exposurePath(home)), 'exposure.env stays 0600 — one writer, one mode').toBe(0o600);
    expect(bytesAt(caddyfilePath(home))).toBe(ipCaddyfile(IP_ADDR, 7788));
    expect(mode(caddyfilePath(home))).toBe(0o644);
    expect(ccrcDirEntries(home)).toEqual(['Caddyfile', 'exposure.env']);
    // No rp id and no ddns anything — the two shapes this arm must NOT have.
    const envBytes = readFileSync(exposurePath(home), 'utf8');
    expect(envBytes).not.toContain('CCRC_RP_ID');
    expect(envBytes).not.toContain('CCRC_DDNS');
  });

  it('refuses when no interface address is a global IPv4 — NAT/CGNAT, the reason named', async () => {
    const home = box('ccrc-expose-ip-nat-');
    stubHostname(home, '192.168.1.50 10.0.0.5 172.31.0.9');
    const r = await runExposeTty(home, ['ip'], []);
    expect(r.code).not.toBe(0);
    expect(r.stdout).toMatch(/no global IPv4/);
    expect(r.stdout).toMatch(/Nothing was written/);
    // The refusal points at the arms that DO work behind NAT.
    expect(r.stdout).toMatch(/ccrc expose duckdns/);
    expect(r.stdout).toMatch(/ccrc expose byo/);
    expect(ccrcDirEntries(home)).toEqual([]);
  });

  it('refuses when the measurement itself answers nothing — and says what it measured', async () => {
    const home = box('ccrc-expose-ip-nohostname-');
    stubHostname(home, null);
    const r = await runExposeTty(home, ['ip'], []);
    expect(r.code).not.toBe(0);
    expect(r.stdout).toMatch(/hostname -I answered: nothing/);
    expect(ccrcDirEntries(home)).toEqual([]);
  });

  it('prints the three-step sudo ceremony PLUS the trust ceremony', async () => {
    const home = box('ccrc-expose-ip-ceremony-');
    stubHostname(home, IP_ADDR);
    const r = await runExposeTty(home, ['ip'], ['']);
    expect(r.code, r.stdout).toBe(0);
    // The same three root steps every arm prints…
    expect(r.stdout).toMatch(/1\. install caddy/);
    expect(r.stdout).toMatch(/2\. sudo install -m 0644 .*Caddyfile \/etc\/caddy\/Caddyfile/);
    expect(r.stdout).toMatch(/3\. sudo systemctl enable --now caddy/);
    // …plus the trust ceremony: the root's path, `caddy trust` for this box,
    // and the two phone platforms at two lines each.
    expect(r.stdout).toContain('/var/lib/caddy/.local/share/caddy/pki/authorities/local/root.crt');
    expect(r.stdout).toMatch(/sudo caddy trust/);
    const lines = r.stdout.split(/\r?\n/);
    const ios = lines.findIndex((l) => /^expose: {3}iOS: /.test(l));
    expect(ios, `no iOS step in:\n${r.stdout}`).toBeGreaterThan(-1);
    expect(lines[ios + 1]).toMatch(/Certificate Trust Settings/);
    const android = lines.findIndex((l) => /^expose: {3}Android: /.test(l));
    expect(android, `no Android step in:\n${r.stdout}`).toBeGreaterThan(-1);
    expect(lines[android + 1]).toMatch(/pick the copied file/);
    // sudo still appears ONLY where a remedy line hands it to the operator:
    // the numbered steps, and the trust ceremony's own `caddy trust` line.
    for (const line of lines.filter((l) => l.includes('sudo'))) {
      expect(line, 'sudo outside the printed remedies')
        .toMatch(/^expose: {3}([23]\. sudo |on this box: sudo caddy trust)/);
    }
  });

  it('says the passphrase-only sentence VERBATIM, and never asks for a passkey re-enrol', async () => {
    const home = box('ccrc-expose-ip-passkeys-');
    stubHostname(home, IP_ADDR);
    const r = await runExposeTty(home, ['ip'], ['']);
    expect(r.code, r.stdout).toBe(0);
    expect(r.stdout).toContain(
      'passkeys need a domain — on a bare IP the gate runs on passphrase login only');
    expect(r.stdout).not.toMatch(/RE-ENROL/);
  });

  it('states its own prerequisite — no DNS, no ACME, no ports forwarded for issuance', async () => {
    // The duckdns/byo landing's port-forward sentence is ACME's, and ACME is
    // exactly what this arm does not do. Its prerequisite is reachability.
    const home = box('ccrc-expose-ip-prereq-');
    stubHostname(home, IP_ADDR);
    const r = await runExposeTty(home, ['ip'], ['']);
    expect(r.code, r.stdout).toBe(0);
    expect(r.stdout).toMatch(/no DNS record and no ACME/);
    expect(r.stdout).not.toMatch(/forward ports 80 and 443/);
    // …and the restart line survives: exposure.env is still boot config.
    // The remedy names a command THIS box has — `systemctl --user restart` on
    // macOS is a second dead end printed at the moment somebody is already
    // following instructions. What is pinned is that the restart is named.
    expect(r.stdout).toMatch(process.platform === 'darwin'
      ? /launchctl kickstart -k gui\/\d+\/app\.ccrc\.ccrc/
      : /systemctl --user restart ccrc\.service/);
  });

  it('the bind address is data on this arm too — in exposure.env AND the Caddyfile', async () => {
    const home = box('ccrc-expose-ip-bind-');
    stubHostname(home, IP_ADDR);
    const r = await runExposeTty(home, ['ip'], ['203.0.113.9']);
    expect(r.code, r.stdout).toBe(0);
    expect(bytesAt(exposurePath(home))).toBe(ipEnv(IP_ADDR, '203.0.113.9'));
    expect(bytesAt(caddyfilePath(home))).toBe(ipCaddyfile(IP_ADDR, 7788, '203.0.113.9'));
  });

  it('is idempotent: a second run is byte-identical — regeneration reproduces, never invents', async () => {
    const home = box('ccrc-expose-ip-idem-');
    stubHostname(home, IP_ADDR);
    expect((await runExposeTty(home, ['ip'], [''])).code).toBe(0);
    const envBefore = bytesAt(exposurePath(home));
    const caddyBefore = bytesAt(caddyfilePath(home));
    const r = await runExposeTty(home, ['ip'], ['']);
    expect(r.code, r.stdout).toBe(0);
    expect(bytesAt(exposurePath(home))).toBe(envBefore);
    expect(bytesAt(caddyfilePath(home))).toBe(caddyBefore);
  });

  it('installs no ddns units and never calls systemctl — there is no record to keep pointed', async () => {
    const home = box('ccrc-expose-ip-nounits-');
    stubHostname(home, IP_ADDR);
    const r = await runExposeTty(home, ['ip'], ['']);
    expect(r.code, r.stdout).toBe(0);
    expect(existsSync(join(home, '.config', 'systemd', 'user'))).toBe(false);
    expect(existsSync(join(home, 'systemctl-poison'))).toBe(false);
  });

  it('the shadow refusal covers this arm too — ccrc.env keys would still be outvoted', () => {
    const home = box('ccrc-expose-ip-shadow-');
    stubHostname(home, IP_ADDR);
    mkdirSync(join(home, '.ccrc'), { recursive: true });
    writeFileSync(envFilePath(home), 'CCRC_AUTH=on\n');
    const r = runPiped(home, ['expose', 'ip']);
    expect(r.code).toBe(1);
    expect(r.stderr).toContain('CCRC_AUTH');
    expect(r.stderr).toMatch(/Nothing was written/);
    expect(existsSync(exposurePath(home))).toBe(false);
  });
});

// ── status ────────────────────────────────────────────────────────────────

describe('ccrc expose status', () => {
  it('says not configured on a box that never ran the verb, at exit 0', () => {
    const home = box('ccrc-expose-status-none-');
    const r = runPiped(home, ['expose', 'status']);
    expect(r.code).toBe(0);
    expect(r.stdout).toMatch(/^expose: not configured/m);
  });

  it('reports the origin, and the token as SET — NEVER the value', () => {
    const home = box('ccrc-expose-status-set-');
    mkdirSync(join(home, '.ccrc'), { recursive: true });
    writeFileSync(exposurePath(home), duckdnsEnv(SUB, TOKEN), { mode: 0o600 });
    const r = runPiped(home, ['expose', 'status']);
    expect(r.code).toBe(0);
    expect(r.stdout).toMatch(/^expose: configured/m);
    expect(r.stdout).toContain(`https://${HOST}`);
    expect(r.stdout).toMatch(/token: SET/);
    expect(r.stdout).not.toContain(TOKEN);
    expect(r.stderr).not.toContain(TOKEN);
  });

  it('reports NOT SET for a byo box — a missing token is a fact, not a fault', () => {
    const home = box('ccrc-expose-status-notset-');
    mkdirSync(join(home, '.ccrc'), { recursive: true });
    writeFileSync(exposurePath(home), byoEnv(BYO_ORIGIN, BYO_RPID), { mode: 0o600 });
    const r = runPiped(home, ['expose', 'status']);
    expect(r.code).toBe(0);
    expect(r.stdout).toMatch(/token: NOT SET/);
  });

  it('an ip box reads as mode ip, passphrase-only — not as a box missing its rp id', () => {
    // Without the mode arm, status would print `(rp id: (missing))` — a fault
    // costume on a box configured exactly as designed.
    const home = box('ccrc-expose-status-ip-');
    mkdirSync(join(home, '.ccrc'), { recursive: true });
    writeFileSync(exposurePath(home), ipEnv(IP_ADDR), { mode: 0o600 });
    const r = runPiped(home, ['expose', 'status']);
    expect(r.code).toBe(0);
    expect(r.stdout).toMatch(/^expose: configured/m);
    expect(r.stdout).toContain(`https://${IP_ADDR}`);
    expect(r.stdout).toMatch(/mode ip/);
    expect(r.stdout).toMatch(/passphrase/);
    expect(r.stdout).not.toMatch(/rp id: \(missing\)/);
  });
});

// ── the duckdns updater units (Task 3, spec D4) ───────────────────────────
// A user timer curling the DuckDNS update endpoint every 5 minutes, reading
// its token from exposure.env AT RUN TIME — the 0644 unit text never becomes
// a second copy of the 0600 secret. Installed by the duckdns arm only (BYO
// domains own their DNS), out of the tree's `deploy/systemd/` templates,
// through the same atomic idiom every other unit lands by.

const unitDir = (home: string): string => join(home, '.config', 'systemd', 'user');
const ddnsUnit = (home: string, ext: 'service' | 'timer'): string =>
  join(unitDir(home), `ccrc-ddns.${ext}`);

describe('ccrc expose: the duckdns updater units', () => {
  // The DuckDNS refresher's Darwin half. systemd splits "what to run" from
  // "when" — a .service plus a .timer, both shipped as templates the installer
  // copies verbatim; launchd has one job with a `StartInterval`, and there is
  // no template to copy because the plist is GENERATED. So what is pinned here
  // is what those two tests are really about: the schedule, and the fact that
  // the 0644 job file never carries the token.
  itDarwin('duckdns installs ONE launchd job (0644) that refreshes every 5 minutes', async () => {
    const home = box('ccrc-expose-ddns-darwin-');
    const r = await runExposeTty(home, ['duckdns'], [SUB, TOKEN, '']);
    expect(r.code, r.stdout).toBe(0);
    const plist = join(home, 'Library', 'LaunchAgents', 'app.ccrc.ccrc-ddns.plist');
    expect(existsSync(plist), 'no ddns job was installed').toBe(true);
    expect(mode(plist), 'job files are read by launchd, not executed').toBe(0o644);
    const body = readFileSync(plist, 'utf8');
    // `OnCalendar=*:0/5` — the same five minutes, in the only unit launchd has.
    expect(body).toContain('<key>StartInterval</key><integer>300</integer>');
    // THE TOKEN IS NEVER IN THIS FILE. launchd cannot read an EnvironmentFile,
    // so the job is a shell that sources the 0600 exposure.env — which is what
    // keeps the secret out of a world-readable plist, exactly as systemd's
    // `${CCRC_DDNS_TOKEN}` expansion does.
    expect(body).toContain('.ccrc/exposure.env');
    expect(body).toContain('${CCRC_DDNS_TOKEN}');
    expect(body, 'the token was inlined into a 0644 file').not.toContain(TOKEN);
  });

  itDarwin('bootouts, enables, then bootstraps app.ccrc.ccrc-ddns — that argv, that order: the job is ARMED, not only written', async () => {
    // The dead-code shape this pins against, found by PR #11's review: the
    // first cut of `_exp_ddns_units` installed the plist and RETURNED, with
    // the bootstrap block below its `return 0` — so on macOS the job file
    // landed, was never bootstrapped, the record never refreshed, and
    // neither the "enabled" nor the "DEGRADED" line could ever print. A
    // sibling of the Linux argv-order test would have caught it; this is it.
    const home = box('ccrc-expose-ddns-darwin-argv-');
    const r = await runExposeTty(home, ['duckdns'], [SUB, TOKEN, ''], { launchctlOk: true });
    expect(r.code, r.stdout).toBe(0);
    const argv = readFileSync(join(home, 'launchctl-argv'), 'utf8')
      .split('\n').filter((l) => l !== '');
    expect(argv[0]).toMatch(/^bootout gui\/\d+\/app\.ccrc\.ccrc-ddns$/);
    expect(argv[1]).toMatch(/^enable gui\/\d+\/app\.ccrc\.ccrc-ddns$/);
    expect(argv[2]).toMatch(/^bootstrap gui\/\d+ \S+\/Library\/LaunchAgents\/app\.ccrc\.ccrc-ddns\.plist$/);
    expect(r.stdout).toMatch(/^expose: app\.ccrc\.ccrc-ddns enabled/m);
    expect(r.stdout).not.toMatch(/DEGRADED/);
  });

  itDarwin('a refusing launchctl DEGRADES, never dies: the job file installed, exit 0, the exact bootstrap command printed', async () => {
    // The sibling of "a failing systemctl DEGRADES". No launchctl stub is
    // planted, so the platform layer's sandbox-HOME guard refuses the call —
    // the same "no manager reachable" shape the Linux poison stands in for.
    const home = box('ccrc-expose-ddns-darwin-degraded-');
    const r = await runExposeTty(home, ['duckdns'], [SUB, TOKEN, '']);
    expect(r.code, r.stdout).toBe(0);
    expect(existsSync(join(home, 'Library', 'LaunchAgents', 'app.ccrc.ccrc-ddns.plist')),
      'the job file must land even when the bootstrap cannot').toBe(true);
    expect(r.stdout).toMatch(/^expose: DEGRADED — could not bootstrap app\.ccrc\.ccrc-ddns/m);
    expect(r.stdout).toMatch(/launchctl bootstrap gui\/\d+ \S*app\.ccrc\.ccrc-ddns\.plist/);
  });

  itLinux('duckdns installs ccrc-ddns.service + ccrc-ddns.timer (0644) — the shipped templates, byte for byte', async () => {
    const home = box('ccrc-expose-ddns-units-');
    const r = await runExposeTty(home, ['duckdns'], [SUB, TOKEN, '']);
    expect(r.code, r.stdout).toBe(0);
    // Byte-equal to the templates: the installer transforms NOTHING, which is
    // half of the never-inlined guarantee below.
    expect(bytesAt(ddnsUnit(home, 'service')))
      .toBe(readFileSync(join(REPO, 'deploy', 'systemd', 'ccrc-ddns.service'), 'utf8'));
    expect(bytesAt(ddnsUnit(home, 'timer')))
      .toBe(readFileSync(join(REPO, 'deploy', 'systemd', 'ccrc-ddns.timer'), 'utf8'));
    expect(mode(ddnsUnit(home, 'service')), 'units are read by systemd, not executed').toBe(0o644);
    expect(mode(ddnsUnit(home, 'timer'))).toBe(0o644);
    // …and the atomic idiom left no temp file beside them.
    expect(readdirSync(unitDir(home)).sort()).toEqual(['ccrc-ddns.service', 'ccrc-ddns.timer']);
    // The contract lines the templates must carry (spec D4 / the plan's
    // interface block) — asserted on the INSTALLED text, the copy systemd reads.
    const svc = readFileSync(ddnsUnit(home, 'service'), 'utf8');
    expect(svc).toContain('EnvironmentFile=%h/.ccrc/exposure.env');
    expect(svc).toContain(
      'ExecStart=/usr/bin/curl -fsS --max-time 30 "https://www.duckdns.org/update?domains=${CCRC_DDNS_DOMAIN}&token=${CCRC_DDNS_TOKEN}&ip="');
    const timer = readFileSync(ddnsUnit(home, 'timer'), 'utf8');
    expect(timer).toContain('OnCalendar=*:0/5');
    expect(timer).toContain('Persistent=true');
    expect(timer).toContain('WantedBy=timers.target');
  });

  itLinux('runs systemctl --user daemon-reload, then enable --now ccrc-ddns.timer — that argv, that order', async () => {
    // The recording stub: every call is one line of argv. daemon-reload FIRST,
    // for `_inst_enable`'s reason — a unit enabled before systemd has read its
    // file is enabled without it.
    const home = box('ccrc-expose-ddns-argv-');
    const r = await runExposeTty(home, ['duckdns'], [SUB, TOKEN, ''], { systemctlOk: true });
    expect(r.code, r.stdout).toBe(0);
    expect(readFileSync(join(home, 'systemctl-argv'), 'utf8')).toBe(
      '--user daemon-reload\n--user enable --now ccrc-ddns.timer\n');
  });

  it('the byo arm installs neither unit and never calls systemctl — DNS is the operator\'s', async () => {
    const home = box('ccrc-expose-ddns-byo-');
    const r = await runExposeTty(home, ['byo'], [BYO_ORIGIN, BYO_RPID, '']);
    expect(r.code, r.stdout).toBe(0);
    expect(existsSync(unitDir(home)), 'byo must not create the unit dir').toBe(false);
    expect(existsSync(join(home, 'systemctl-poison')), 'byo must not touch systemctl').toBe(false);
  });

  itLinux('the installed service reads the token from the EnvironmentFile — ${CCRC_DDNS_TOKEN} literally, NEVER the value', async () => {
    // The mutation this pins: substitute the token at generation time and the
    // 0644 unit file becomes a world-readable second copy of the secret.
    const home = box('ccrc-expose-ddns-token-');
    const r = await runExposeTty(home, ['duckdns'], [SUB, TOKEN, '']);
    expect(r.code, r.stdout).toBe(0);
    const svc = readFileSync(ddnsUnit(home, 'service'), 'utf8');
    expect(svc).toContain('${CCRC_DDNS_TOKEN}');
    expect(svc).not.toContain(TOKEN);
  });

  itLinux('a failing systemctl DEGRADES, never dies: units installed, exit 0, the exact commands printed', async () => {
    // `_inst_linger`'s doctrine at this verb's scale: the poisoned systemctl
    // (exit 97) is this suite's stand-in for "no session bus", and a run whose
    // files all landed must not abort over a thing one command fixes. The
    // operator is told the command; doctor (Task 4) will carry the rest.
    const home = box('ccrc-expose-ddns-degraded-');
    const r = await runExposeTty(home, ['duckdns'], [SUB, TOKEN, '']);   // default env: systemctl exits 97
    expect(r.code, r.stdout).toBe(0);
    expect(existsSync(ddnsUnit(home, 'service'))).toBe(true);
    expect(existsSync(ddnsUnit(home, 'timer'))).toBe(true);
    expect(r.stdout).toMatch(
      /systemctl --user daemon-reload && systemctl --user enable --now ccrc-ddns\.timer/);
  });
});

// ── the bind address, and the class of loss it stands for ─────────────────
//
// Everything below is one incident (2026-08-21/22) turned into mechanism. A
// box running `tailscale serve` already holds :443, so stock caddy — which
// binds every address — could not start. The cure was one `bind` line, added
// BY HAND to a file `ccrc expose` regenerates from scratch. It survived only
// because nobody re-ran the verb.

describe('ccrc expose: the bind address is DATA, not a hand edit', () => {
  it('duckdns: an answer lands in exposure.env AND in the Caddyfile', async () => {
    const home = box('ccrc-expose-bind-duck-');
    const r = await runExposeTty(home, ['duckdns'], [SUB, TOKEN, '203.0.113.9']);
    expect(r.code, r.stdout).toBe(0);
    expect(bytesAt(exposurePath(home))).toBe(duckdnsEnv(SUB, TOKEN, '203.0.113.9'));
    expect(bytesAt(caddyfilePath(home))).toBe(caddyfile(HOST, 7788, '203.0.113.9'));
  });

  it('byo: the same, on the other arm', async () => {
    const home = box('ccrc-expose-bind-byo-');
    const r = await runExposeTty(home, ['byo'], [BYO_ORIGIN, BYO_RPID, '198.51.100.4']);
    expect(r.code, r.stdout).toBe(0);
    expect(bytesAt(exposurePath(home))).toBe(byoEnv(BYO_ORIGIN, BYO_RPID, '198.51.100.4'));
    expect(bytesAt(caddyfilePath(home))).toBe(caddyfile(BYO_RPID, 7788, '198.51.100.4'));
  });

  it('REGENERATION REPRODUCES IT — the whole point, measured across two runs', async () => {
    // The defect was not "no bind directive". It was that the only way to get
    // one was an edit the next run deleted. So the assertion is not that run 1
    // writes it — it is that run 2, told nothing, writes it again.
    const home = box('ccrc-expose-bind-regen-');
    expect((await runExposeTty(home, ['duckdns'], [SUB, TOKEN, '203.0.113.9'])).code).toBe(0);
    const first = bytesAt(caddyfilePath(home));
    const again = await runExposeTty(home, ['duckdns'], [SUB, TOKEN, '203.0.113.9']);
    expect(again.code, again.stdout).toBe(0);
    expect(bytesAt(caddyfilePath(home))).toBe(first);
    expect(bytesAt(caddyfilePath(home))).toContain('bind 203.0.113.9');
  });

  it('blank is a real answer: no key, no directive, caddy takes every address', async () => {
    // Absence must not become `CCRC_CADDY_BIND=`, which is a line that decides
    // nothing and which every `_box_env_value` reader would treat as unset
    // anyway — an empty distinction at a seam.
    const home = box('ccrc-expose-bind-blank-');
    const r = await runExposeTty(home, ['duckdns'], [SUB, TOKEN, '']);
    expect(r.code, r.stdout).toBe(0);
    expect(readFileSync(exposurePath(home), 'utf8')).not.toContain('CCRC_CADDY_BIND');
    expect(readFileSync(caddyfilePath(home), 'utf8')).not.toContain('bind');
  });

  it.each([
    ['a space',  '203.0.113.9 extra'],
    ['a brace',  '203.0.113.9}'],
    ['a hash',   '203.0.113.9#c'],
  ])('refuses %s — it would land verbatim as a Caddyfile directive', async (_what, bad) => {
    const home = box('ccrc-expose-bind-bad-');
    const r = await runExposeTty(home, ['duckdns'], [SUB, TOKEN, bad]);
    expect(r.code).not.toBe(0);
    expect(r.stdout).toMatch(/whitespace, a brace or a '#'/);
    expect(r.stdout).toMatch(/Nothing was written/);
    // The refusal is worth nothing if it leaves the files behind it.
    expect(ccrcDirEntries(home)).toEqual([]);
  });

  it('status reports the bind, and says so plainly when there is none', async () => {
    const home = box('ccrc-expose-bind-status-');
    expect((await runExposeTty(home, ['duckdns'], [SUB, TOKEN, '203.0.113.9'])).code).toBe(0);
    expect(runPiped(home, ['expose', 'status']).stdout).toMatch(/caddy binds 203\.0\.113\.9/);

    const bare = box('ccrc-expose-bind-status-none-');
    expect((await runExposeTty(bare, ['duckdns'], [SUB, TOKEN, ''])).code).toBe(0);
    expect(runPiped(bare, ['expose', 'status']).stdout).toMatch(/caddy binds every address/);
  });
});

describe('ccrc expose: a regeneration never destroys in silence', () => {
  it('an edited Caddyfile is KEPT under ~/ccrc-backups and named in the transcript', async () => {
    // D-164. The operator's `log` block and hand-added `bind` were real work.
    // "Regenerated" is the contract; losing them without a word is not.
    const home = box('ccrc-expose-preserve-');
    expect((await runExposeTty(home, ['duckdns'], [SUB, TOKEN, ''])).code).toBe(0);
    const edited = `${HOST} {\n    bind 203.0.113.9\n    log { format json }\n    reverse_proxy 127.0.0.1:7788\n}\n`;
    writeFileSync(caddyfilePath(home), edited);

    const r = await runExposeTty(home, ['duckdns'], [SUB, TOKEN, '']);
    expect(r.code, r.stdout).toBe(0);
    // regenerated…
    expect(bytesAt(caddyfilePath(home))).toBe(caddyfile(HOST, 7788));
    // …but the previous bytes exist, and the run SAID where.
    const said = r.stdout.match(/kept at (\S+\/Caddyfile)/);
    expect(said, `no backup path in transcript:\n${r.stdout}`).toBeTruthy();
    const kept = said![1].replace(/^~/, home);
    expect(readFileSync(kept, 'utf8')).toBe(edited);
    expect(kept.startsWith(join(home, 'ccrc-backups'))).toBe(true);
  });

  it('an UNCHANGED Caddyfile takes no backup — noise is its own defect', async () => {
    const home = box('ccrc-expose-preserve-noop-');
    expect((await runExposeTty(home, ['duckdns'], [SUB, TOKEN, ''])).code).toBe(0);
    const r = await runExposeTty(home, ['duckdns'], [SUB, TOKEN, '']);
    expect(r.code, r.stdout).toBe(0);
    expect(r.stdout).not.toMatch(/kept at/);
    expect(existsSync(join(home, 'ccrc-backups'))).toBe(false);
  });
});

describe('ccrc expose: exposure implies arming', () => {
  it('writes CCRC_AUTH=on — a public box is armed or it is published', async () => {
    // D-162. Measured: a deploy shipped a ccrc.env with no CCRC_AUTH line and
    // a publicly-reachable box came back unauthenticated. The key now belongs
    // to the file deploy does not ship.
    const home = box('ccrc-expose-arms-');
    const r = await runExposeTty(home, ['duckdns'], [SUB, TOKEN, '']);
    expect(r.code, r.stdout).toBe(0);
    expect(readFileSync(exposurePath(home), 'utf8')).toContain('CCRC_AUTH=on');
  });

  it('says DEGRADED when the box has no passphrase — armed with no credential refuses everyone', async () => {
    const home = box('ccrc-expose-arms-nopass-');
    const r = await runExposeTty(home, ['duckdns'], [SUB, TOKEN, '']);
    expect(r.code, r.stdout).toBe(0);
    expect(r.stdout).toMatch(/DEGRADED .* no passphrase/);
    expect(r.stdout).toMatch(/ccrc passwd/);
  });

  it('is quiet about the passphrase when the box already has one', async () => {
    const home = box('ccrc-expose-arms-haspass-');
    mkdirSync(join(home, '.ccrc'), { recursive: true });
    writeFileSync(join(home, '.ccrc', 'auth.scrypt'), 'fixture-not-a-real-hash\n', { mode: 0o600 });
    const r = await runExposeTty(home, ['duckdns'], [SUB, TOKEN, '']);
    expect(r.code, r.stdout).toBe(0);
    expect(r.stdout).not.toMatch(/DEGRADED .* no passphrase/);
  });

  it('refuses when ccrc.env already sets CCRC_AUTH — two files, one winner, silently', async () => {
    // The D3 shadow refusal, extended to the key it now writes. An operator
    // who armed by hand in ccrc.env must not have this verb outvote them.
    const home = box('ccrc-expose-arms-shadow-');
    mkdirSync(join(home, '.ccrc'), { recursive: true });
    writeFileSync(join(home, '.ccrc', 'ccrc.env'), 'CCRC_AUTH=on\n');
    const r = await runExposeTty(home, ['duckdns'], [SUB, TOKEN, '']);
    expect(r.code).not.toBe(0);
    expect(r.stdout).toMatch(/CCRC_AUTH/);
    expect(r.stdout).toMatch(/Nothing was written/);
    expect(existsSync(exposurePath(home))).toBe(false);
  });
});
